apiVersion: v1
kind: Service
metadata:
  labels:
    app: id-generator-svc
  name: id-generator-svc
  namespace: unique-id-generator
spec:
  ports:
    - name: 8081-8080
      port: 8081
      protocol: TCP
      targetPort: 8080
  selector:
    app: id-generator
  type: ClusterIP
status:
  loadBalancer: {}